name = "myagenda"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Cloudflare Pages output dir (generato da @cloudflare/next-on-pages)
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "myagenda-db"
database_id = "25f38048-8a56-40a7-9ef2-70a19d96ce7d"

[[r2_buckets]]
binding = "R2"
bucket_name = "myagenda-uploads"
